name: protocol_handler
description: This plugin allows Flutter apps to register and handle custom protocols (i.e. deep linking).
version: 0.1.3
homepage: https://github.com/leanflutter/protocol_handler

platforms:
  ios:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  win32_registry: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.protocol_handler
        pluginClass: ProtocolHandlerPlugin
      ios:
        pluginClass: ProtocolHandlerPlugin
      macos:
        pluginClass: ProtocolHandlerPlugin
      windows:
        pluginClass: ProtocolHandlerPlugin
