name: protocol_handler_platform_interface
description: A common platform interface for the protocol_handler plugin.
version: 0.2.0
homepage: https://github.com/leanflutter/protocol_handler/blob/main/packages/protocol_handler_platform_interface

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1
