name: protocol_handler_example
description: Demonstrates how to use the protocol_handler plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bot_toast: ^4.0.1
  flutter:
    sdk: flutter
  preference_list: ^0.0.1
  protocol_handler:
    path: ../
  window_manager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  uses-material-design: true
