name: protocol_handler_ios
description: iOS implementation of the protocol_handler plugin.
version: 0.2.0
repository: https://github.com/leanflutter/protocol_handler/tree/main/packages/protocol_handler_ios


environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  protocol_handler_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    implements: protocol_handler
    platforms:
      ios:
        pluginClass: ProtocolHandlerIosPlugin
